### ISSUE TITLE
S3 Alarm example when certain bucket becomes public

### ISSUE THREAD

**Issue by tigran10** [marbot-io/monitoring-jump-start#32]
Hey guys, just wondering if you can add an example for S3 alarms. 

  - If private bucket turned into public
  - if a certain bucket turned into public

Thanks,

**Comment by michaelwittig** [comment]
Hi @tigran10 
[AWS Security Hub](https://aws.amazon.com/security-hub/) detects public buckets and creates a finding. marbot connects to Security Hub and presents the findings in Slack / Microsoft Teams to you. Let me know if that approach works for you?

**Comment by tigran10** [comment]
hey @michaelwittig sorry for replying late on this one, was actually trying to find a moment to book a "marbot intro" with you, as we have subscribed to it now.

AWS Security hub approach seems to be a good one. I guess we would have a way to whitelist `expected public` findings there right?

**Comment by michaelwittig** [comment]
@tigran10 SecurityHub Findings have a "lifecycle" in SecurityHub.

1. Click on [Findings](https://console.aws.amazon.com/securityhub/home#/findings?search=ComplianceStatus%3D%255Coperator%255C%253AEQUALS%255C%253AFAILED%26SeverityNormalized%3D70%252C100) on the left
    a. Search for Status is Failed
    b. and Severity (normalized) in range 70 to 100
   c. You can skip all previous steps by clicking on the Details link in the message from marbot in Slack/Microsoft Teams
2. All findings should have Workflow status New assigned 
3. For each findings, you can now assign one of the following values:
    a. Notified: You are working on the problem
    b. Suppressed: Ignore
    c. Resolved: The findings should disappear within 12 hours when Security Hub runs the next check cycle.
    d. If the workflow status stays at New, you will receive a message from marbot every day.

Let me know if this approach works for you. We also appreciate your feedback on how we could improve the Security Hub integration.

PS: You can also disable entire checks in SecurityHub. Click on [Security standards](https://console.aws.amazon.com/securityhub/home#/standards) on the left, select the standard (e.g., AWS Foundational Security Best Practices v1.0.0), select the check and click the **Disable** button**.

PS2: Looking forward to talk to you during an onboarding session!

**Comment by michaelwittig** [comment]
PS3: If you [update to the latest Jump Start version](https://github.com/marbot-io/monitoring-jump-start#update-procedure) we will automatically set the workflow status to `Notified` while we forward findings to marbot...
